// Nightly Alpha Arena digest — generates a markdown report of leaderboard,
// top trades, and reasoning→outcome notes for the creator.
const API = 'http://localhost:8000';

async function j(path) {
  const r = await fetch(API + path);
  if (!r.ok) throw new Error(`${path}: ${r.status}`);
  return r.json();
}

async function digest() {
  const [board, stats, agents] = await Promise.all([
    j('/leaderboard'), j('/trade-stats'), j('/agents')
  ]);
  const nameOf = Object.fromEntries(agents.map(a => [a.id, a.name]));
  const lines = [`# Alpha Arena Digest — ${new Date().toISOString().slice(0, 10)}`, ''];
  lines.push('## Leaderboard');
  lines.push('| # | Agent | ROI | Sharpe | WinRate | MaxDD |');
  lines.push('|---|-------|-----|--------|---------|-------|');
  board.forEach((e, i) => {
    lines.push(`| ${i + 1} | ${e.agent_name || nameOf[e.agent_id] || e.agent_id} | ` +
      `${fmt(e.roi_pct ?? e.roi)} | ${fmt(e.sharpe)} | ${fmt(e.win_rate)} | ${fmt(e.max_drawdown)} |`);
  });
  lines.push('', '## Trade stats (realized)');
  for (const s of stats) {
    lines.push(`- **${nameOf[s.agent_id] || s.agent_id}**: wins ${s.wins ?? '?'} / losses ${s.losses ?? '?'}, ` +
      `total PnL ${fmt(s.total_pnl ?? s.realized_pnl)}`);
  }
  // top trades of the current #1
  const top = board[0];
  if (top) {
    lines.push('', `## Latest reasoning from #1 (${nameOf[top.agent_id]})`);
    try {
      const trades = await j(`/trades/agents/${top.agent_id}?limit=5`);
      for (const t of trades) {
        lines.push(`- \`${t.symbol}\` ${t.side} @ ${t.entry_price ?? '?'} — ${(t.reasoning || '').slice(0, 300)}`);
      }
    } catch (e) { lines.push(`(trades unavailable: ${e.message})`); }
  }
  lines.push('', '_Generated by Nerd (automaton). Will convert to nightly cron + email on creator approval._');
  return lines.join('\n');
}

function fmt(v) { return v == null ? '?' : (typeof v === 'number' ? +v.toFixed(3) : v); }

digest().then(r => { console.log(r); require('fs').writeFileSync('DIGEST.md', r); })
  .catch(e => { console.error('digest failed:', e.message); process.exit(1); });
