// Study top Alpha Arena traders: correlate reasoning keywords → realized outcomes.
// Produces LESSONS.md so I can improve my own trade reasoning before competing.
const API = 'http://localhost:8000';

async function j(p) { const r = await fetch(API + p); if (!r.ok) throw new Error(p + ':' + r.status); return r.json(); }

(async () => {
  const [board, stats] = await Promise.all([j('/leaderboard'), j('/trade-stats')]);
  const agents = await j('/agents');
  const nameOf = Object.fromEntries(agents.map(a => [a.id, a.name]));
  const statBy = Object.fromEntries(stats.map(s => [s.agent_id, s]));

  const report = [`# Arena Lessons — ${new Date().toISOString().slice(0, 10)}`, ''];
  // ranked list with realized pnl
  const ranked = board.map(e => {
    const s = statBy[e.agent_id] || {};
    return { name: nameOf[e.agent_id], roi: e.roi_pct ?? e.roi, pnl: s.total_pnl, wins: s.wins, losses: s.losses, id: e.agent_id };
  }).sort((a, b) => (b.roi || 0) - (a.roi || 0));

  report.push('## Ranking (ROI + realized PnL)');
  for (const r of ranked) report.push(`- **${r.name}**: ROI ${(100 * (r.roi || 0)).toFixed(2)}%, realized ${r.pnl ?? 0}, W/L ${r.wins ?? 0}/${r.losses ?? 0}`);

  // fetch trades for best and worst, extract patterns
  const best = ranked[0], worst = ranked[ranked.length - 1];
  for (const [label, a] of [['BEST', best], ['WORST', worst]]) {
    report.push('', `## ${label}: ${a.name}`);
    try {
      const trades = await j(`/trades/agents/${a.id}?limit=20`);
      let wins = 0, n = 0, confSum = 0, confN = 0;
      const words = {};
      for (const t of trades) {
        n++;
        const ok = (t.realized_pnl ?? t.pnl) > 0; if (ok) wins++;
        if (t.confidence != null) { confSum += t.confidence; confN++; }
        for (const w of (t.reasoning || '').toLowerCase().match(/[a-z]{4,}/g) || []) words[w] = (words[w] || 0) + 1;
      }
      report.push(`- ${n} trades, ${wins} profitable, avg confidence ${confN ? (confSum / confN).toFixed(2) : '?'}`);
      report.push('- common reasoning words: ' + Object.entries(words).sort((x, y) => y[1] - x[1]).slice(0, 15).map(([w, c]) => `${w}(${c})`).join(', '));
      report.push('- sample: ' + (trades[0]?.reasoning || '').slice(0, 200));
    } catch (e) { report.push(`- trades unavailable: ${e.message}`); }
  }
  report.push('', '_Auto-generated by Nerd for reasoning-improvement study._');
  const out = report.join('\n');
  require('fs').writeFileSync('LESSONS.md', out);
  console.log(out);
})().catch(e => { console.error(e); process.exit(1); });
